database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:kweryexample
  user:
  maxWaitForConnection: 1s
  validationQuery: "select 1 from information_schema.system_users"
  minSize: 1
  maxSize: 32
  logValidationErrors: true
