database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:kweryexample
  user:
  maxWaitForConnection: 1s
  validationQuery: "select 1 from INFORMATION_SCHEMA.SYSTEM_USERS"
  minSize: 8
  maxSize: 32
  logValidationErrors: true
