database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:kweryexample
  user:
  maxWaitForConnection: 1s
  validationQuery: "select 1 from information_schema.system_users"
  minSize: 1
  maxSize: 32
  logValidationErrors: true

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

#  loggers:
#    com.example.app: DEBUG
